"""
monitoring/trade_journal.py — Structured Trade Logging

Responsibilities:
- Record every trade event as a structured JSON log entry
- Each entry includes: signal details, sizing, entry, exit, P&L, and reasoning
- Support both file-based logging and in-memory log for testing
- Produce a session summary at end of trading day

Log entry types:
    SIGNAL     : Signal generated by signal_engine (not yet traded)
    ORDER      : Order submitted to broker
    FILL       : Order filled (position opened)
    EXIT       : Position closed (SL / TP / manual)
    REJECTED   : Signal rejected by risk or validator
    HALT       : Session halt event

Every entry is a standalone JSON object — one per line (JSONL format).
This enables easy parsing, filtering, and analysis with jq or pandas.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger(__name__)


class TradeJournal:
    """
    Structured trade journal that writes JSONL log entries.

    Usage:
        journal = TradeJournal(log_dir="logs/", session_id="2024-01-15")
        journal.log_signal(signal, sizing_result)
        journal.log_fill(order)
        journal.log_exit(order)
    """

    def __init__(
        self,
        log_dir: str = "logs/",
        session_id: Optional[str] = None,
        in_memory: bool = False,
    ) -> None:
        self.session_id = session_id or datetime.utcnow().strftime("%Y-%m-%d_%H%M%S")
        self.in_memory = in_memory
        self._entries: list[dict] = []

        if not in_memory:
            self._log_dir = Path(log_dir)
            self._log_dir.mkdir(parents=True, exist_ok=True)
            self._log_path = self._log_dir / f"journal_{self.session_id}.jsonl"
        else:
            self._log_path = None

    def log_signal(self, signal: Any, sizing: Optional[Any] = None) -> None:
        """Log a generated trade signal."""
        entry = self._base_entry("SIGNAL", signal.signal_id)
        entry.update({
            "symbol": signal.symbol,
            "direction": signal.direction,
            "bar_index": signal.bar_index,
            "timestamp": str(signal.timestamp),
            "entry_price": signal.entry_price,
            "stop_loss": signal.stop_loss,
            "take_profit": signal.take_profit,
            "risk_reward": signal.risk_reward,
            "strat_pattern": signal.strat_pattern,
            "htf_bias": signal.htf_bias,
            "ict_event": signal.ict_event,
            "fvg_zone": list(signal.fvg_zone),
            "swept_level": signal.swept_level,
            "strength": signal.strength,
            "gates_passed": signal.gates_passed,
        })
        if sizing:
            entry["sizing"] = {
                "contracts": sizing.contracts,
                "risk_dollars": sizing.risk_dollars,
                "risk_pct": sizing.risk_pct,
                "approved": sizing.approved,
            }
        self._write(entry)

    def log_order(self, order: Any) -> None:
        """Log an order submission."""
        entry = self._base_entry("ORDER", order.signal_id)
        entry.update({
            "order_id": order.order_id,
            "symbol": order.symbol,
            "side": order.side,
            "quantity": order.quantity,
            "order_type": order.order_type,
            "limit_price": order.limit_price,
            "stop_price": order.stop_price,
            "take_profit_price": order.take_profit_price,
        })
        self._write(entry)

    def log_fill(self, order: Any) -> None:
        """Log an order fill (position opened)."""
        entry = self._base_entry("FILL", order.signal_id)
        entry.update({
            "order_id": order.order_id,
            "symbol": order.symbol,
            "side": order.side,
            "quantity": order.quantity,
            "fill_price": order.fill_price,
            "fill_time": str(order.fill_time),
            "commission": order.commission,
        })
        self._write(entry)

    def log_exit(self, order: Any) -> None:
        """Log a position close (stop, TP, or manual)."""
        entry = self._base_entry("EXIT", order.signal_id)
        entry.update({
            "order_id": order.order_id,
            "symbol": order.symbol,
            "side": order.side,
            "quantity": order.quantity,
            "fill_price": order.fill_price,
            "close_price": order.close_price,
            "close_time": str(order.close_time),
            "realized_pnl": order.realized_pnl,
            "commission": order.commission,
            "exit_reason": order.notes,
        })
        self._write(entry)

    def log_rejection(self, signal_id: str, reason: str, checks_failed: list[str]) -> None:
        """Log a trade rejection."""
        entry = self._base_entry("REJECTED", signal_id)
        entry.update({
            "reason": reason,
            "checks_failed": checks_failed,
        })
        self._write(entry)

    def log_halt(self, reason: str) -> None:
        """Log a session halt event."""
        entry = self._base_entry("HALT", "session")
        entry["reason"] = reason
        self._write(entry)

    def log_custom(self, event_type: str, context_id: str, data: dict) -> None:
        """Log an arbitrary structured event."""
        entry = self._base_entry(event_type, context_id)
        entry.update(data)
        self._write(entry)

    def get_entries(self, event_type: Optional[str] = None) -> list[dict]:
        """
        Return in-memory entries (only available when in_memory=True).
        Optionally filter by event_type.
        """
        if not self.in_memory:
            raise RuntimeError("get_entries() is only available when in_memory=True")
        if event_type:
            return [e for e in self._entries if e.get("event_type") == event_type]
        return list(self._entries)

    def session_summary(self) -> dict:
        """Compute and return a summary of this session's journal entries."""
        fills = [e for e in self._entries if e.get("event_type") == "FILL"]
        exits = [e for e in self._entries if e.get("event_type") == "EXIT"]
        signals = [e for e in self._entries if e.get("event_type") == "SIGNAL"]
        rejections = [e for e in self._entries if e.get("event_type") == "REJECTED"]

        pnls = [e.get("realized_pnl", 0) for e in exits if e.get("realized_pnl") is not None]
        total_pnl = sum(pnls)
        wins = sum(1 for p in pnls if p > 0)

        return {
            "session_id": self.session_id,
            "signals_generated": len(signals),
            "trades_opened": len(fills),
            "trades_closed": len(exits),
            "trades_rejected": len(rejections),
            "total_pnl": round(total_pnl, 2),
            "wins": wins,
            "losses": len(pnls) - wins,
            "win_rate_pct": round(wins / len(pnls) * 100, 1) if pnls else 0.0,
        }

    # ------------------------------------------------------------------
    # Private
    # ------------------------------------------------------------------

    def _base_entry(self, event_type: str, context_id: str) -> dict:
        return {
            "event_type": event_type,
            "context_id": context_id,
            "session_id": self.session_id,
            "logged_at": datetime.utcnow().isoformat() + "Z",
        }

    def _write(self, entry: dict) -> None:
        self._entries.append(entry)
        if not self.in_memory and self._log_path:
            with open(self._log_path, "a") as f:
                f.write(json.dumps(entry) + "\n")
